# Copyright Amazon.com, Inc. or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
version: 0.2

phases:
  install:
    commands:
      - set -e
      # Populate Required Variables
      - DEFAULT_PATH=$(pwd)
      - TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
      - TF_S3_BUCKET=$(aws ssm get-parameter --name $SSM_TF_S3_BUCKET --query "Parameter.Value" --output text)
      - TF_S3_KEY=$VENDED_ACCOUNT_ID-customizations-pipeline/terraform.tfstate
      - TF_BACKEND_REGION=$(aws ssm get-parameter --name $SSM_TF_BACKEND_REGION --query "Parameter.Value" --output text)
      - TF_KMS_KEY_ID=$(aws ssm get-parameter --name $SSM_TF_KMS_KEY_ID --query "Parameter.Value" --output text)
      - TF_DDB_TABLE=$(aws ssm get-parameter --name $SSM_TF_DDB_TABLE --query "Parameter.Value" --output text)
      - TF_VERSION=$(aws ssm get-parameter --name $SSM_TF_VERSION --query "Parameter.Value" --output text)
      - TF_DISTRIBUTION=$(aws ssm get-parameter --name $SSM_TF_DISTRIBUTION --query "Parameter.Value" --output text)


      # Configure Development SSH Key
      - |
        ssh_key_parameter=$(aws ssm get-parameter --name /aft/config/aft-ssh-key --with-decryption 2> /dev/null || echo "None")
        if [[ $ssh_key_parameter != "None" ]]; then
          ssh_key=$(jq --raw-output ".Parameter.Value" <<< $ssh_key_parameter)
          mkdir -p ~/.ssh
          echo "Host *" >> ~/.ssh/config
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          echo "UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          echo "$ssh_key" > ~/.ssh/ssh_key
          echo -e "\n\n" >>  ~/.ssh/ssh_key
          chmod 600 ~/.ssh/ssh_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/ssh_key
        fi

      # Clone AFT
      - AWS_MODULE_SOURCE=$(aws ssm get-parameter --name $SSM_AWS_MODULE_SOURCE --query "Parameter.Value" --output text)
      - AWS_MODULE_GIT_REF=$(aws ssm get-parameter --name $SSM_AWS_MODULE_GIT_REF --query "Parameter.Value" --output text)
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - git clone --quiet -b $AWS_MODULE_GIT_REF $AWS_MODULE_SOURCE aws-aft-core-framework

      # Generate session profiles
      - chmod +x $DEFAULT_PATH/aws-aft-core-framework/sources/scripts/creds.sh
      - $DEFAULT_PATH/aws-aft-core-framework/sources/scripts/creds.sh

      # Install Terraform
      - |
        cd /tmp
        if [ "$TF_DISTRIBUTION" = "oss" ]; then
          echo "Installing Terraform"
          curl -o terraform_${TF_VERSION}_linux_amd64.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
          unzip -o terraform_${TF_VERSION}_linux_amd64.zip && mv terraform /usr/bin
          terraform -no-color --version
        else
          echo "Installing Tofu"
          curl -L -o tofu_${TF_VERSION}_linux_amd64.zip https://github.com/opentofu/opentofu/releases/download/v${TF_VERSION}/tofu_${TF_VERSION}_linux_amd64.zip
          unzip -o tofu_${TF_VERSION}_linux_amd64.zip && mv tofu /usr/bin
          tofu -no-color --version
        fi

      # Install Python Dependencies
      - python3 -m venv ./venv
      - source ./venv/bin/activate
      - pip install -U pip
      - pip install jinja2-cli==0.7.0 Jinja2==3.0.1 requests==2.26.0

  pre_build:
    on-failure: ABORT
    commands:
      # Get AFT admin role ARN for assume_role in providers
      - AFT_MGMT_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
      - AFT_EXEC_ROLE_ARN=arn:$AWS_PARTITION:iam::$AFT_MGMT_ACCOUNT:role/AWSAFTExecution
      - cd $DEFAULT_PATH/aws-aft-core-framework/sources/aft-customizations-common/templates/customizations_pipeline
      - |
        if ls *.jinja >/dev/null 2>&1; then
          for f in *.jinja; do
            jinja2 "$f" -D timestamp="$TIMESTAMP" -D region="$TF_BACKEND_REGION" -D bucket="$TF_S3_BUCKET" \
              -D key="$TF_S3_KEY" -D dynamodb_table="$TF_DDB_TABLE" -D kms_key_id="$TF_KMS_KEY_ID" \
              -D tf_version="$TF_VERSION" -D tf_distribution_type="$TF_DISTRIBUTION" \
              -D target_admin_role_arn="$AFT_EXEC_ROLE_ARN" >> "$(basename "$f" .jinja).tf"
          done
        else
          echo "No Jinja2 templates found - skipping template processing"
        fi
      - for f in *.tf; do echo "\n \n"; echo $f; cat $f; done
  build:
    on-failure: ABORT
    commands:
      - export AWS_PROFILE=aft-management-admin
      - |
        if [ "$TF_DISTRIBUTION" = "spacelift" ]; then
          echo "Spacelift distribution detected - creating Spacelift stack for customizations pipeline"
          
          # Get Spacelift configuration from SSM
          SPACELIFT_API_ENDPOINT=$(aws ssm get-parameter --name "/aft/config/spacelift/api-endpoint" --query "Parameter.Value" --output text)
          SPACELIFT_API_KEY_ID=$(aws ssm get-parameter --name "/aft/config/spacelift/api-key-id" --with-decryption --query "Parameter.Value" --output text)
          SPACELIFT_API_KEY_SECRET=$(aws ssm get-parameter --name "/aft/config/spacelift/api-key-secret" --with-decryption --query "Parameter.Value" --output text)
          SPACELIFT_SPACE_NAME=$(aws ssm get-parameter --name "/aft/config/spacelift/space-name" --query "Parameter.Value" --output text)
          SPACELIFT_PARENT_SPACE_ID=$(aws ssm get-parameter --name "/aft/config/spacelift/parent-space-id" --query "Parameter.Value" --output text)
          SPACELIFT_IAC_VENDOR=$(aws ssm get-parameter --name "/aft/config/spacelift/iac-vendor" --query "Parameter.Value" --output text)
          SPACELIFT_INTEGRATION_ROLE_ARN=$(aws ssm get-parameter --name "/aft/config/spacelift/integration-role-arn" --query "Parameter.Value" --output text 2>/dev/null || echo "")
          SPACELIFT_INTEGRATION_NAME=$(aws ssm get-parameter --name "/aft/config/spacelift/integration-name" --query "Parameter.Value" --output text 2>/dev/null || echo "")
          SPACELIFT_STACK_NAME="$VENDED_ACCOUNT_ID-customizations-pipeline"
          
          echo "Spacelift VCS Configuration:"
          echo "  Stack: $SPACELIFT_STACK_NAME"
          echo "  Terraform files directory: $DEFAULT_PATH/aws-aft-core-framework/sources/aft-customizations-common/templates/customizations_pipeline"
          
          cd $DEFAULT_PATH
          python3 $DEFAULT_PATH/aws-aft-core-framework/sources/scripts/spacelift_manager.py \
            --operation "deploy" \
            --space_name "$SPACELIFT_SPACE_NAME" \
            --parent_space_id "$SPACELIFT_PARENT_SPACE_ID" \
            --stack_name "$SPACELIFT_STACK_NAME" \
            --terraform_files_dir "$DEFAULT_PATH/aws-aft-core-framework/sources/aft-customizations-common/templates/customizations_pipeline" \
            --api_endpoint "$SPACELIFT_API_ENDPOINT" \
            --api_key_id "$SPACELIFT_API_KEY_ID" \
            --api_key_secret "$SPACELIFT_API_KEY_SECRET" \
            --vendor "$SPACELIFT_IAC_VENDOR" \
            --integration_role_arn $SPACELIFT_INTEGRATION_ROLE_ARN \
            --integration_name $SPACELIFT_INTEGRATION_NAME \
            --env "TF_VAR_account_id=$VENDED_ACCOUNT_ID"
        elif [ "$TF_DISTRIBUTION" = "oss" ]; then
          terraform init -no-color
          terraform apply -var="account_id=$VENDED_ACCOUNT_ID" -no-color --auto-approve
        else
          tofu init -no-color
          tofu apply -var="account_id=$VENDED_ACCOUNT_ID" -no-color --auto-approve
        fi
